/**
 * Content-script HMR scaffolding (Phase 6).
 *
 * Plasmo punts on this: "content script output changes require extension
 * reload for consistency". ExtForge can do better by routing content scripts
 * through `chrome.scripting.registerContentScripts()` from the background SW
 * instead of the static manifest entry.
 *
 * Architecture:
 *   1. Builder emits a tiny static bootstrap that the manifest references.
 *      The bootstrap connects to the HMR server and listens for "swap" calls.
 *   2. Background SW (with the `scripting` permission, auto-injected in dev
 *      mode) calls `chrome.scripting.registerContentScripts([{ id, matches,
 *      js: [<latest-bundle-url>], runAt }])` on startup AND on every HMR
 *      update.
 *   3. On change, background calls `unregister` then `register` to swap.
 *      Existing tabs receive a message and call user-supplied `dispose()`
 *      hooks before re-import()ing the new bundle (same module-level
 *      `import.meta.hot.accept` mechanism as Phase 4 popups, but applied
 *      to content-script context).
 *
 * What's in this file: types + the dispose registry runtime + the manifest
 * augmentation helper. The actual chrome.scripting wiring is generated as a
 * dev-only background snippet (`generateContentScriptHMRBootstrap`) that the
 * builder injects when `dev: true && manifest.contentScripts` is non-empty.
 *
 * What's deferred: dynamic registration is gated on `extforge.config.ts`
 * opt-in (`hmr.contentScripts: 'dynamic'`) so the default behaviour stays
 * the simple manifest-static path. Until it's exercised end-to-end in
 * tests-e2e, treat dynamic mode as experimental.
 */

export interface ContentScriptHMRDescriptor {
  /** Stable id — index in the user's `contentScripts` array. */
  id: number;
  /** Match patterns. */
  matches: string[];
  /** Path to the bundled JS, relative to the per-browser dist root. */
  js: string;
  /** Optional runAt timing. Default: 'document_idle'. */
  runAt?: 'document_start' | 'document_end' | 'document_idle';
}

/**
 * Generates a TypeScript-source background snippet that registers each
 * content script dynamically and re-registers them on HMR updates. Called by
 * the builder ONLY in dev mode AND only when the user has opted in via
 * `extforge.config.ts` `hmr.contentScripts: 'dynamic'`.
 */
export function generateContentScriptHMRBootstrap(
  descriptors: ContentScriptHMRDescriptor[],
): string {
  const json = JSON.stringify(descriptors, null, 2);
  return `// Generated by extforge — content-script HMR bootstrap
const __extforge_cs_descriptors__ = ${json};

async function __extforge_register__() {
  const chrome = (globalThis as { chrome?: typeof globalThis.chrome }).chrome;
  if (!chrome?.scripting?.registerContentScripts) return;
  const ids = __extforge_cs_descriptors__.map(d => 'extforge-cs-' + d.id);
  try { await chrome.scripting.unregisterContentScripts({ ids }); } catch {}
  await chrome.scripting.registerContentScripts(
    __extforge_cs_descriptors__.map(d => ({
      id: 'extforge-cs-' + d.id,
      matches: d.matches,
      js: [d.js + '?t=' + Date.now()],
      runAt: d.runAt ?? 'document_idle',
      world: 'ISOLATED' as const,
    }))
  );
}

await __extforge_register__();

// On HMR full-reload triggered by content-script JS change, re-register so
// new tabs (and re-injected existing tabs) load the latest bundle.
if (typeof self !== 'undefined' && (self as unknown as { __EXTFORGE_REREGISTER__?: () => void }).__EXTFORGE_REREGISTER__ !== '__set__') {
  (self as unknown as { __EXTFORGE_REREGISTER__: () => Promise<void> }).__EXTFORGE_REREGISTER__ = __extforge_register__;
}
`;
}

/**
 * Per-tab dispose registry runtime — the bit of code injected into every
 * dynamically-registered content script. User code calls
 * `__extforgeDispose__(() => cleanup())` to register teardown for HMR swaps.
 */
export const CONTENT_SCRIPT_HMR_RUNTIME = `
// extforge content-script HMR runtime
(function() {
  if ((globalThis as any).__extforge_cs_inited__) return;
  (globalThis as any).__extforge_cs_inited__ = true;
  const disposers: Array<() => void> = [];
  (globalThis as { __extforgeDispose__?: (cb: () => void) => void }).__extforgeDispose__ = (cb) => disposers.push(cb);
  // When a new copy of this script is registered + injected, the OLD
  // disposers run first via a message to the prior instance.
  if ((globalThis as { chrome?: typeof globalThis.chrome }).chrome?.runtime?.onMessage) {
    chrome.runtime.onMessage.addListener((msg) => {
      if (msg?.__extforge === 'cs-dispose') {
        for (const d of disposers) try { d(); } catch {}
        disposers.length = 0;
      }
    });
  }
})();
`.trim();
