import { describe, expect, it } from 'vitest';
import { deepMergeManifest } from '../src/core/modules/merge.js';
import { ModuleRegistry } from '../src/core/modules/registry.js';
import { defineModule } from '../src/core/modules/types.js';
import type { PluginContext, PluginHooks } from '../src/core/plugins/types.js';

describe('deepMergeManifest', () => {
  it('concatenates and de-dupes arrays', () => {
    const base = { permissions: ['storage', 'tabs'] };
    const patch = { permissions: ['tabs', 'offscreen'] };
    expect(deepMergeManifest(base, patch)).toEqual({
      permissions: ['storage', 'tabs', 'offscreen'],
    });
  });

  it('merges nested objects recursively', () => {
    const base = { background: { service_worker: 'bg.js' } };
    const patch = { background: { type: 'module' } };
    expect(deepMergeManifest(base, patch)).toEqual({
      background: { service_worker: 'bg.js', type: 'module' },
    });
  });

  it('overwrites primitives', () => {
    expect(deepMergeManifest({ name: 'a' }, { name: 'b' })).toEqual({ name: 'b' });
  });

  it('leaves base untouched when patch is not an object', () => {
    const base = { name: 'a' };
    expect(deepMergeManifest(base, null as never)).toBe(base);
  });
});

/** Builds a minimal PluginContext double for exercising ModuleRegistry.toPlugin(). */
function fakePluginContext(): {
  ctx: PluginContext;
  manifestTransforms: Array<(m: Record<string, unknown>, b: 'chrome') => unknown>;
  addedEntries: Array<{ name: string; file: string }>;
} {
  const manifestTransforms: Array<(m: Record<string, unknown>, b: 'chrome') => unknown> = [];
  const addedEntries: Array<{ name: string; file: string }> = [];
  const hooks: PluginHooks = {
    onConfigResolved: () => {},
    onManifestTransform: (fn) => {
      manifestTransforms.push(fn as never);
    },
    onBuildStart: () => {},
    onBuildEntry: () => {},
    onBuildEnd: () => {},
    onCssTransform: () => {},
    onDevReload: () => {},
  };
  const ctx = {
    config: {},
    paths: { root: '/root', src: '/root/src', dist: '/root/dist' },
    logger: { debug() {}, info() {}, warn() {}, error() {} } as never,
    hooks,
    addEntry: (entry: { name: string; file: string }) => {
      addedEntries.push(entry);
    },
    emitFile: () => {},
  } as unknown as PluginContext;
  return { ctx, manifestTransforms, addedEntries };
}

describe('ModuleRegistry', () => {
  it('adapts a module into a v1 plugin that reuses addEntry for addEntrypoint', async () => {
    const registry = new ModuleRegistry();
    const mod = defineModule({
      name: 'test-module',
      setup(ctx) {
        ctx.addEntrypoint({ name: 'offscreen', input: 'src/offscreen.ts' });
      },
    });
    const plugin = registry.toPlugin(mod);
    expect(plugin.name).toBe('test-module');
    expect(plugin.apiVersion).toBe(1);

    const { ctx, addedEntries } = fakePluginContext();
    await plugin.setup(ctx);

    expect(addedEntries).toEqual([
      {
        name: 'offscreen',
        file: 'src/offscreen.ts',
        format: 'esm',
        isContentScript: undefined,
        esbuildOptions: undefined,
      },
    ]);
  });

  it('extendManifest registers a manifest-transform hook that deep-merges', async () => {
    const registry = new ModuleRegistry();
    const mod = defineModule({
      name: 'test-module',
      setup(ctx) {
        ctx.extendManifest({ permissions: ['offscreen'] });
      },
    });
    const plugin = registry.toPlugin(mod);
    const { ctx, manifestTransforms } = fakePluginContext();
    await plugin.setup(ctx);

    expect(manifestTransforms).toHaveLength(1);
    const result = manifestTransforms[0]({ permissions: ['storage'] }, 'chrome');
    expect(result).toEqual({ permissions: ['storage', 'offscreen'] });
  });

  it('tracks per-module contributions for doctor', async () => {
    const registry = new ModuleRegistry();
    const mod = defineModule({
      name: 'analytics',
      setup(ctx) {
        ctx.addEntrypoint({ name: 'offscreen', input: 'src/offscreen.ts' });
        ctx.extendManifest({ permissions: ['offscreen'] });
        ctx.addTypeDeclaration('declare module "foo" {}');
        ctx.addRuntimeImport('useAnalytics', './runtime/analytics.js');
      },
    });
    const plugin = registry.toPlugin(mod);
    const { ctx } = fakePluginContext();
    await plugin.setup(ctx);

    expect(registry.getContributions()).toEqual([
      {
        module: 'analytics',
        entrypoints: ['offscreen'],
        manifestPatches: 1,
        typeDeclarations: 1,
        runtimeImports: ['useAnalytics'],
      },
    ]);
    expect(registry.getTypeDeclarationsFile()).toContain('declare module "foo" {}');
    expect(registry.getRuntimeImportsFile()).toBe(
      [
        '// Generated by ExtForge modules. Do not edit by hand.',
        'export { useAnalytics } from "./runtime/analytics.js";',
      ].join('\n'),
    );
  });

  it('returns undefined for generated files when no module contributed them', async () => {
    const registry = new ModuleRegistry();
    const mod = defineModule({ name: 'noop', setup() {} });
    const plugin = registry.toPlugin(mod);
    const { ctx } = fakePluginContext();
    await plugin.setup(ctx);

    expect(registry.getTypeDeclarationsFile()).toBeUndefined();
    expect(registry.getRuntimeImportsFile()).toBeUndefined();
    expect(registry.getContributions()).toEqual([
      {
        module: 'noop',
        entrypoints: [],
        manifestPatches: 0,
        typeDeclarations: 0,
        runtimeImports: [],
      },
    ]);
  });
});
