import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { build } from '../src/core/builder/index.js';
import { loadExtForgeConfig } from '../src/core/config.js';
import { modulesActiveCheck } from '../src/core/doctor/checks/modules-active.js';
import type { ModuleRegistry } from '../src/core/modules/registry.js';
import { createLogger, LogLevel } from '../src/core/logger/index.js';

const silent = createLogger({ level: LogLevel.Silent });

describe('module system integration', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'extforge-modules-'));
    mkdirSync(join(root, 'src/background'), { recursive: true });
    writeFileSync(join(root, 'src/background/index.ts'), 'export const start = () => 1;\n');
    writeFileSync(join(root, 'src/offscreen-entry.ts'), 'console.log("offscreen");\n');
    writeFileSync(join(root, 'package.json'), '{}');
    writeFileSync(join(root, 'tsconfig.json'), '{}');
  });

  afterEach(() => {
    try {
      rmSync(root, { recursive: true, force: true });
    } catch {}
  });

  function writeConfig(): void {
    writeFileSync(
      join(root, 'extforge.config.ts'),
      `export default {
         browsers: ['chrome'],
         framework: 'vanilla',
         manifest: { name: 'x', version: '0.0.1', manifestVersion: 3,
           permissions: { required: [], optional: [], host: [] },
           background: { entrypoint: 'background/index.js' } },
         modules: [{
           name: 'test-analytics-module',
           setup(ctx) {
             ctx.addEntrypoint({ name: 'offscreen', input: 'src/offscreen-entry.ts' });
             ctx.extendManifest({ permissions: ['offscreen'] });
             ctx.addTypeDeclaration('declare const useAnalytics: () => void;');
             ctx.addRuntimeImport('useAnalytics', './runtime.js');
           },
         }],
       };`,
    );
  }

  it('a module can add an entrypoint, extend the manifest, and contribute types', async () => {
    writeConfig();
    const cfg = await loadExtForgeConfig(root);
    const result = await build(root, cfg, { browser: 'chrome', dev: false }, silent);
    expect(result.errors).toHaveLength(0);

    // addEntrypoint bundled a synthetic entry.
    expect(existsSync(join(root, 'dist/chrome/offscreen.js'))).toBe(true);

    // extendManifest merged into the permissions array (manifest schema
    // flattens the required/optional/host object form into a plain array).
    const manifest = JSON.parse(readFileSync(join(root, 'dist/chrome/manifest.json'), 'utf8'));
    expect(manifest.permissions).toContain('offscreen');

    // addTypeDeclaration / addRuntimeImport wrote generated project-root files.
    const dts = readFileSync(join(root, '.extforge/modules.d.ts'), 'utf8');
    expect(dts).toContain('declare const useAnalytics');
    const runtime = readFileSync(join(root, '.extforge/modules.ts'), 'utf8');
    expect(runtime).toBe(
      [
        '// Generated by ExtForge modules. Do not edit by hand.',
        'export { useAnalytics } from "./runtime.js";',
      ].join('\n'),
    );
  }, 30_000);

  it('existing plugins keep working alongside modules', async () => {
    writeFileSync(
      join(root, 'extforge.config.ts'),
      `export default {
         browsers: ['chrome'],
         framework: 'vanilla',
         manifest: { name: 'x', version: '0.0.1', manifestVersion: 3,
           permissions: { required: [], optional: [], host: [] },
           background: { entrypoint: 'background/index.js' } },
         modules: [{
           name: 'perm-module',
           setup(ctx) { ctx.extendManifest({ permissions: ['offscreen'] }); },
         }],
         plugins: [{
           name: 'description-stamp', apiVersion: 1,
           setup({ hooks }) { hooks.onManifestTransform((m) => ({ ...m, description: 'stamped' })); },
         }],
       };`,
    );
    const cfg = await loadExtForgeConfig(root);
    await build(root, cfg, { browser: 'chrome', dev: false }, silent);
    const manifest = JSON.parse(readFileSync(join(root, 'dist/chrome/manifest.json'), 'utf8'));
    expect(manifest.permissions).toContain('offscreen');
    expect(manifest.description).toBe('stamped');
  }, 30_000);

  it('extforge doctor lists active modules and their contributions', async () => {
    writeConfig();
    const cfg = await loadExtForgeConfig(root);
    const registry = (cfg as { __moduleRegistry?: ModuleRegistry }).__moduleRegistry!;
    expect(registry.getContributions()).toEqual([
      {
        module: 'test-analytics-module',
        entrypoints: ['offscreen'],
        manifestPatches: 1,
        typeDeclarations: 1,
        runtimeImports: ['useAnalytics'],
      },
    ]);

    const result = await modulesActiveCheck.run({ cwd: root });
    expect(result.status).toBe('info');
    expect(result.message).toContain('test-analytics-module');
    expect(result.message).toContain('offscreen');
  });

  it('reports no modules when none are configured', async () => {
    writeFileSync(
      join(root, 'extforge.config.ts'),
      `export default {
         browsers: ['chrome'],
         framework: 'vanilla',
         manifest: { name: 'x', version: '0.0.1', manifestVersion: 3,
           permissions: { required: [], optional: [], host: [] },
           background: { entrypoint: 'background/index.js' } },
       };`,
    );
    const result = await modulesActiveCheck.run({ cwd: root });
    expect(result.status).toBe('info');
    expect(result.message).toBe('No modules configured');
  });

  it('rejects a module missing setup()', async () => {
    writeFileSync(
      join(root, 'extforge.config.ts'),
      `export default {
         browsers: ['chrome'],
         modules: [{ name: 'broken' }],
       };`,
    );
    await expect(loadExtForgeConfig(root)).rejects.toThrow(/not a valid ExtForge module/);
  });

  it('resolves a local file-path module specifier', async () => {
    mkdirSync(join(root, 'modules'), { recursive: true });
    writeFileSync(
      join(root, 'modules/my-module.ts'),
      `export default {
         name: 'local-module',
         setup(ctx) { ctx.extendManifest({ permissions: ['storage'] }); },
       };`,
    );
    writeFileSync(
      join(root, 'extforge.config.ts'),
      `export default {
         browsers: ['chrome'],
         framework: 'vanilla',
         manifest: { name: 'x', version: '0.0.1', manifestVersion: 3,
           permissions: { required: [], optional: [], host: [] },
           background: { entrypoint: 'background/index.js' } },
         modules: ['./modules/my-module'],
       };`,
    );
    const cfg = await loadExtForgeConfig(root);
    await build(root, cfg, { browser: 'chrome', dev: false }, silent);
    const manifest = JSON.parse(readFileSync(join(root, 'dist/chrome/manifest.json'), 'utf8'));
    expect(manifest.permissions).toContain('storage');
  }, 30_000);
});
