import type { ExtForgePluginV1, ManifestObject, PluginContext } from '../plugins/types.js';
import { deepMergeManifest } from './merge.js';
import type {
  EntrypointDescriptor,
  ExtForgeModule,
  ModuleContext,
  ModuleContribution,
} from './types.js';

interface ContributionRecord {
  entrypoints: Set<string>;
  manifestPatches: number;
  typeDeclarations: string[];
  runtimeImports: Map<string, string>;
}

function newRecord(): ContributionRecord {
  return {
    entrypoints: new Set(),
    manifestPatches: 0,
    typeDeclarations: [],
    runtimeImports: new Map(),
  };
}

/**
 * Adapts `ExtForgeModule`s into `ExtForgePluginV1`s so they flow through the
 * existing `PluginRunner` — entrypoints, manifest transforms, and emitted
 * files all reuse the plugin build-time wiring unchanged. On top of that, it
 * tracks what each module contributed (for `extforge doctor`) and collects
 * the type-declaration / runtime-import text modules hand it, which the
 * builder writes to `.extforge/` once per build.
 *
 * Execution order: modules run in the order they're declared in
 * `modules: [...]`, interleaved with plugins only insofar as the caller
 * places the adapted plugins in that combined list (see `config.ts`, which
 * runs built-ins, then modules, then user plugins).
 */
export class ModuleRegistry {
  private readonly records = new Map<string, ContributionRecord>();
  private readonly typeDeclarations: string[] = [];
  private readonly runtimeImports: Array<{ name: string; from: string }> = [];

  toPlugin(mod: ExtForgeModule): ExtForgePluginV1 {
    return {
      name: mod.name,
      apiVersion: 1,
      setup: async (pluginCtx: PluginContext) => {
        const record = newRecord();
        this.records.set(mod.name, record);

        const moduleCtx: ModuleContext = {
          ...pluginCtx,
          addEntrypoint: (entry: EntrypointDescriptor) => {
            record.entrypoints.add(entry.name);
            pluginCtx.addEntry({
              name: entry.name,
              file: entry.input,
              format: entry.format ?? 'esm',
              isContentScript: entry.isContentScript,
              esbuildOptions: entry.esbuildOptions,
            });
          },
          extendManifest: (patch) => {
            record.manifestPatches++;
            pluginCtx.hooks.onManifestTransform((manifest, browser) => {
              const resolved = typeof patch === 'function' ? patch(manifest, browser) : patch;
              return deepMergeManifest(manifest, resolved as ManifestObject);
            });
          },
          addTypeDeclaration: (dts: string) => {
            record.typeDeclarations.push(dts);
            this.typeDeclarations.push(`// from module: ${mod.name}\n${dts}`);
          },
          addRuntimeImport: (name: string, from: string) => {
            record.runtimeImports.set(name, from);
            const existing = this.runtimeImports.find((r) => r.name === name);
            if (existing) {
              if (existing.from !== from) {
                throw new Error(
                  `Runtime import "${name}" already registered from ${JSON.stringify(existing.from)}; cannot re-register from ${JSON.stringify(from)}`,
                );
              }
              return;
            }
            this.runtimeImports.push({ name, from });
          },
        };
        await mod.setup(moduleCtx);
      },
    };
  }

  /** Per-module contribution summary, in setup order — used by `extforge doctor`. */
  getContributions(): ModuleContribution[] {
    return [...this.records.entries()].map(([module, r]) => ({
      module,
      entrypoints: [...r.entrypoints],
      manifestPatches: r.manifestPatches,
      typeDeclarations: r.typeDeclarations.length,
      runtimeImports: [...r.runtimeImports.keys()],
    }));
  }

  /** Concatenated `.d.ts` source from every module, or `undefined` if none contributed any. */
  getTypeDeclarationsFile(): string | undefined {
    if (this.typeDeclarations.length === 0) return undefined;
    return [
      '// Generated by ExtForge modules. Do not edit by hand.',
      ...this.typeDeclarations,
    ].join('\n\n');
  }

  /** Generated runtime-import barrel, or `undefined` if no module registered one. */
  getRuntimeImportsFile(): string | undefined {
    if (this.runtimeImports.length === 0) return undefined;
    return [
      '// Generated by ExtForge modules. Do not edit by hand.',
      ...this.runtimeImports.map((r) => `export { ${r.name} } from ${JSON.stringify(r.from)};`),
    ].join('\n');
  }
}
