// Generated by extforge — content-script HMR bootstrap
const __extforge_cs_descriptors__: Array<{
  id: number;
  matches: string[];
  js: string;
  runAt?: 'document_start' | 'document_end' | 'document_idle';
  excludeMatches?: string[];
  allFrames?: boolean;
  world?: 'MAIN' | 'ISOLATED';
}> = {{DESCRIPTORS_JSON}};

async function __extforge_register__() {
  const chrome = (globalThis as { chrome?: typeof globalThis.chrome }).chrome;
  if (!chrome?.scripting?.registerContentScripts) return;
  const ids = __extforge_cs_descriptors__.map(d => 'extforge-cs-' + d.id);
  try { await chrome.scripting.unregisterContentScripts({ ids }); } catch {}
  await chrome.scripting.registerContentScripts(
    __extforge_cs_descriptors__.map(d => ({
      id: 'extforge-cs-' + d.id,
      matches: d.matches,
      js: [d.js + '?t=' + Date.now()],
      runAt: d.runAt ?? 'document_idle',
      ...(d.excludeMatches ? { excludeMatches: d.excludeMatches } : {}),
      ...(d.allFrames === undefined ? {} : { allFrames: d.allFrames }),
      world: d.world ?? ('ISOLATED' as const),
    }))
  );
}

await __extforge_register__();

// On HMR full-reload triggered by content-script JS change, re-register so
// new tabs (and re-injected existing tabs) load the latest bundle.
if (typeof self !== 'undefined' && (self as unknown as { __EXTFORGE_REREGISTER__?: () => void }).__EXTFORGE_REREGISTER__ !== '__set__') {
  (self as unknown as { __EXTFORGE_REREGISTER__: () => Promise<void> }).__EXTFORGE_REREGISTER__ = __extforge_register__;
}
